#!/bin/sh -x

CURRENT_VERSION=`head -n 1 VERSION` || exit 1
FILES=`grep -l 'version: installer' * | grep '[ch]$'` || exit 1

for f in ${FILES}
do
  sed -E "s/version: installer [0-9]+\.[0-9]+\.[0-9]+/version: ${CURRENT_VERSION}/g" < $f > $f.tmp || exit 1
  mv "$f.tmp" "$f" || exit 1
done
