#!/bin/sh

if [ $# -lt 2 ]
then
  echo "usage: basename objects ..." 1>&2
  exit 1
fi

LD_TYPE=`head -n 1 conf-ldtype`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-ldtype" 1>&2
  exit 1
fi
LD=`head -n 1 conf-ld`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-ld" 1>&2
  exit 1
fi
SYS_TYPE=`head -n 1 conf-systype`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-systype" 1>&2
  exit 1
fi
SO_SUFFIX=`head -n 1 conf-sosuffix`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-sosuffix" 1>&2
  exit 1
fi

main="$1"
shift

libname=`./mk-libname "${main}"`
if [ $? -ne 0 ]
then
  echo "fatal: could not execute ./mk-libname" 1>&2
  exit 1
fi

rm -f "${libname}"

case "${LD_TYPE}" in
  gcc)
    case "${SYS_TYPE}" in
      darwin)
        libtool -dynamic -o "${libname}" ${1+"$@"} -lc
        ;;
      sunos)
        ld -G -z text -o "${libname}" ${1+"$@"} -lc
        ;;
      cygwin*)
        ${LD} -shared -o "${libname}" ${1+"$@"}
        ;;
      *)
        ${LD} -shared -Wl,-soname,"${libname}" -o "${libname}" ${1+"$@"} -lc
        ;;
    esac
    ;;
  hp-c)
    ${LD} -b -o "${libname}" ${1+"$@"}
    ;;
  compaq-c)
    ${LD} -no_archive -shared -o "${libname}" ${1+"$@"}
    ;;
  intel-c)
    ${LD} -shared -o "${libname}" ${1+"$@"}
    ;;
  sun-c)
    ${LD} -G -z text -o "${libname}" ${1+"$@"}
    ;;
  *)
    echo "fatal: unknown compiler - cannot produce shared objects" 1>&2
    exit 1
    ;;
esac

if [ $? -ne 0 ]
then
  exit 1
fi
echo "${libname}" >> "${main}".vlb
