rmdir /usr/lib 
error: rmdir: /usr/lib - access denied
unlink /usr/lib/file.so.0.2 
error: unlink: /usr/lib/file.so.0.2 - file does not exist
unlink /usr/lib/xyz.a 
error: unlink: /usr/lib/xyz.a - file does not exist
unlink libfile.so 
error: unlink: libfile.so - file does not exist
unlink libxyz.a 
error: unlink: libxyz.a - file does not exist
unlink testlib 
error: unlink: testlib - file does not exist
unlink imagdir 
error: chdir: /usr/nonexistant/dir - file does not exist
unlink /usr/lib/nonexistant 
error: unlink: /usr/lib/nonexistant - file does not exist
error: directory not defined
error: from file not defined
error: from file not defined
error: from file not defined
error: from file not defined
error: no such user '1234XNOBODYx123'
