mkdir /usr/lib 755 root:wheel
install files/file.so.0.2 /usr/lib/file.so.0.2 444 root:wheel
install files/xyz.a /usr/lib/xyz.a 444 root:wheel
symlink file.so.0.2 libfile.so 444 
symlink xyz.a libxyz.a 444 
symlink /usr/lib testlib 755 
symlink /imaginary/dir imagdir 755 
install nonexistant /usr/lib/nonexistant 444 root:wheel
error: directory not defined
error: from file not defined
error: from file not defined
error: from file not defined
error: from file not defined
error: no such user '1234XNOBODYx123'
