-- files do not exist before testing
check installto/t1 -1:-1 755 directory
failed: file does not exist
check installto/t1/file.c -1:-1 600 file
failed: file does not exist
check installto/t1/nonexistant -1:-1 600 file
failed: file does not exist
check installto/t1/renamed.c -1:-1 600 file
failed: file does not exist
check installto/t1/symlink -1:-1 600 symlink
failed: file does not exist

-- deinstaller objects to removing nonexistant files
unlink installto/t1/symlink
failed: unlink: file does not exist
unlink installto/t1/renamed.c
failed: unlink: file does not exist
unlink installto/t1/nonexistant
failed: unlink: file does not exist
unlink installto/t1/file.c
failed: unlink: file does not exist
rmdir installto/t1
failed: rmdir: file does not exist

-- installer installs files, directories and symlinks
mkdir installto/t1 1001:0 755
copy files/t1/file.c installto/t1/file.c 1001:0 600
copy files/t1/nonexistant installto/t1/nonexistant 1001:0 600
error: open: file does not exist
copy files/t1/file.c installto/t1/renamed.c 1001:0 600
link installto/t1 file.c symlink

-- instchk checks existence and attributes
check installto/t1 -1:-1 755 directory
check installto/t1/file.c -1:-1 600 file
check installto/t1/nonexistant -1:-1 600 file
failed: file does not exist
check installto/t1/renamed.c -1:-1 600 file
check installto/t1/symlink -1:-1 600 symlink

-- deinstaller removes files, directories and symlinks
unlink installto/t1/symlink
unlink installto/t1/renamed.c
unlink installto/t1/nonexistant
failed: unlink: file does not exist
unlink installto/t1/file.c
rmdir installto/t1

-- files have definitely been removed 
check installto/t1 -1:-1 755 directory
failed: file does not exist
check installto/t1/file.c -1:-1 600 file
failed: file does not exist
check installto/t1/nonexistant -1:-1 600 file
failed: file does not exist
check installto/t1/renamed.c -1:-1 600 file
failed: file does not exist
check installto/t1/symlink -1:-1 600 symlink
failed: file does not exist

